export default constants = {
  IC_MATERIAL_COMMUNITY: 'Material Community',
  IC_FEATHER: 'Feather',

  NO_INTERNET: 'No Internet',
  INTERNET_ACCESS_ERROR: 'Please check your internet connection',
  NO_INTERNET_SNACKBAR_MESSAGE: 'Internet not available',
  UNKNOWN_ERROR: 'Error Detected',
  UNKNOWN_ERROR_MESSAGE: 'There was an error',

  NO_DATA_FOUND: 'OOOPSS!',
  NO_DATA_FOUND_Message: 'No data found',

  TXT_EMAIL_ADDRESS: 'Email',
  TXT_PASSWORD: 'Password',
  TXT_FORGOT_PASSWORD: 'Forgot Password?',
  TXT_NOT_SIGNED_UP: "Haven't signed up yet?",
  TXT_SIGN_UP: 'Sign Up',
  TXT_MOBILE_NUMBER: 'Mobile Number',
  TXT_NAME: 'Name',
  TXT_LOCATION: 'Location',
  TXT_TITLE: 'Title',
  TXT_DESCRIPTION: 'Description/ Question',

  TXT_FIRST_NAME: 'First Name',
  TXT_LAST_NAME: 'Last Name',
  TXT_STORE_NAME: 'Store Name',
  TXT_ADDRESS: 'Address',
  TXT_CITY: 'City',
  TXT_PINCODE: 'Pincode',
  TXT_STATE: 'State',
  TXT_COUNTRY: 'Country',
  TXT_DOMAIN: 'Domain',
  TXT_CATEGORY: 'Category',
  TXT_FACEBOOK: 'Facebook',
  TXT_LINKEDIN: 'LinkedIn',
  TXT_CHARGES: 'Charges',
  TXT_TYPE: 'Type',
  TXT_MINORDER: 'Minimum Order Value For Free Delivery',
  TXT_KEY: 'Key',
  TXT_SECRET: 'Secret',
  TXT_RESET_PASS: 'Reset password',
  TXT_USERNAME: 'Username',
  TXT_LOGOUT: "Logout",
  TXT_PRODUCT_NAME: 'Product Name',
  TXT_SUB_CATEGORY: 'Sub Category',
  TXT_BRAND: 'Brand',
  TXT_BASE_PRICE: 'Base Price',
  TXT_WEIGHT: 'Weight',
  TXT_EDIT_QUANTITY: 'Quantity of Product',
  TXT_VARIANT: 'Variant',
  TXT_SIZE: 'Size',
  TXT_COLOR: 'Color',
  TXT_SKU_NUMBER: 'SKU Number',
  TXT_QUANTITY: 'Quantity',
  TXT_SELLING_PRICE: 'Selling Price',
  TXT_MRP: 'MRP',
  TXT_ADD_NEW_PRODUCT: "Add New Product",
  TXT_MANAGE_PRODUCT: "Manage Product",
  TXT_ADD_CATEGORY: "Add Category",
  TXT_EDIT_CATEGORY: "Edit Category",
  TXT_ADD_SUB_CATEGORY: "Add Sub Category",
  TXT_IMAGE_RECOM_20: 'Recommended Size: 20px*20px',
  TXT_VARIANT_iMAGE_UPLOAD: 'Add Image Variant',
  TXT_CATEGORY_NAME: 'Category Name',
  TXT_EDIT_SUB_CATEGORY: 'Edit Sub Category',
  TXT_SUB_CATEGORY_NAME: 'Sub Category Name',
  TXT_ADD_PROMOTIONAL_CATEGORY: 'Add Promotional Category',
  TXT_EDIT_PROMOTIONAL_CATEGORY: 'Edit Promotional Category',
  TXT_ADD_PROMOTIONAL_PRODUCT: 'Add Promotional Product',
  TXT_ADD_COUPON: 'Add Coupon',
  TXT_EDIT_COUPON: 'Edit Coupon',
  TXT_ADD_BRAND: 'Add Brand',
  TXT_ADD_BRAND_AND_MANUFACTURER: 'Add Brand & Manufacturer',
  TXT_EDIT_BRAND: 'Edit Brand',
  TXT_ADD_PRODUCT_ATTRIBUTE: 'Add Product Attribute',
  TXT_EDIT_PRODUCT_ATTRIBUTE: 'Edit Product Attribute',
  TXT_ADD_VARIANT_VALUE: 'Add Variant Value',
  TXT_EDIT_VARIANT_VALUE: 'Edit Variant Value',
  TXT_ADD_MESSAGE: "Add Message",
  TXT_EDIT_MESSAGE: "Edit Message",


  EVNT_UPDATE_SETUP_STORE: 'updatedSetupStore',


  ERROR_USERNAME: 'Please enter your username',
  ERROR_EMAIL: 'Please enter your email id',
  ERROR_PASSWORD: 'Please enter your password',
  ERROR_MOBILE: 'Please enter your mobile number',
  ERROR_NAME: 'Please enter your name',
  ERROR_LOCATION: 'Please enter your location',
  ERROR_FIRST_NAME: 'Please enter your first name',
  ERROR_LAST_NAME: 'Please enter your last name',
  ERROR_STORE_NAME: 'Please enter your store name',
  ERROR_ADDRESS: 'Please enter your address',
  ERROR_CITY: 'Please enter your city',
  ERROR_PINCODE: 'Please enter your pincode',
  ERROR_STATE: 'Please enter your state',
  ERROR_COUNTRY: 'Please enter your country',
  ERROR_DOMAIN: 'Please enter your domain',
  ERROR_CATEGORY: 'Please enter your category',
  ERROR_FACEBOOK: 'Please enter your facebook link',
  ERROR_LINKEDIN: 'Please enter your linkedin link',
  ERROR_CHARGES: 'Please enter your charges',
  ERROR_TYPE: 'Please enter your type',
  ERROR_MINORDER: 'Please enter your minimum order value',
  ERROR_KEY: 'Please enter your key',
  ERROR_SECRET: 'Please enter your secret',

  ERROR_EMAILV: 'Please enter valid email address',
  ERROR_PASSWORDV:
    'Password must be at least 5 characters long with atleast one symbol and one number',
  ERROR_MOBILEV: 'Please enter valid mobile number',

  PARAM_TITLE: 'title',
  PARAM_SHOW_VARIANT: 'show variant',
  PARAM_SETUP_STORE_INDEX: 'setup store index',

  USER_DATA: 'USER_DATA',
  SETUP_STORE_DATA: 'SETUP_STORE_DATA',

  FIREBASE_TOKEN: 'FIREBASE',
};
