import React from "react";
import LocalizedStrings from "react-native-localization";

const setOfStrings = new LocalizedStrings({
    en: {
        login: "Login",
        username: "Username",
        password: "Password",
        forgotPassword: "Forgot Password?",
        resetPassword: "Reset Password",
        dontHaveAccount: "Don't have an account?",
        signUp: "Sign Up",
        skip: "Skip",
        submit : "Submit",
        hey: "Hey",
        overview: "Overview",
        totalCrops: "Total Crops",
        totalFarmArea: "Total Farm Area",
        totalDiseasedCrop: "Total Diseased Crop",
        totalProduction: "Total Production",
        productionDetails: "Production Details",
        jan: "Jan",
        feb: "Feb",
        mar: "Mar",
        apr: "Apr",
        may: "May",
        jun: "Jun",
        recentPrecautions: "Recent Precautions",
        addImage: "Add Image",
        recomSize: "Recommended Size: 165px*65px",
        checkForDisease: "Check For Disease",
        expertAdvice: "Expert Advice",
        disease: "Disease",
        crop: "Crop",
        causes: "Causes",
        treatment: "Treatment",
        tutorial: "Tutorial",
    },
    hi: {
        login: "लॉग इन करें",
        username: "उपयोगकर्ता नाम",
        password: "पासवर्ड",
        forgotPassword: "पासवर्ड भूल गए?",
        resetPassword: "पासवर्ड रीसेट करें",
        dontHaveAccount: "खाता नहीं है?",
        signUp: "साइन अप करें",
        skip: "छोड़ें",
        submit : "प्रस्तुत करें",
        hey: "हैलो",
        overview: "अवलोकन",
        totalCrops: "कुल फसल",
        totalFarmArea: "कुल कृषि क्षेत्र",
        totalDiseasedCrop: "कुल रोगी फसल",
        totalProduction: "कुल उत्पाद",
        productionDetails: "उत्पाद विवरण",
        jan: "जनवरी",
        feb: "फरवरी",
        mar: "मार्च",
        apr: "अप्रैल",
        may: "मई",
        jun: "जून",
        recentPrecautions: "हाल की बचाव",
        addImage: "छवि जोड़ें",
        recomSize: "अनुशंसित आकार: 165px * 65px",
        checkForDisease: "रोग की जाँच करें",
        expertAdvice: "विशेषज्ञ सलाह",
        disease: "बीमारी",
        crop: "फसल",
        causes: "कारण",
        treatment: "इलाज",
        tutorial: "ट्यूटोरियल",
    },
    ma: {
        login: "लॉग इन करें",
        username: "उपयोगकर्ता नाम",
        password: "पासवर्ड",
        forgotPassword: "पासवर्ड भूल गए?",
        resetPassword: "पासवर्ड रीसेट करें",
        dontHaveAccount: "खाता नह ीं है?",
        signUp: "साइन अप करें",
        skip: "छोड़ें",
        submit : "प्रस्तुत करें",
        hey: "नमस्कार",
        overview: "अवलोकन",
        totalCrops: "कुल फसल",
        totalFarmArea: "कुल कृषि क्षेत्र",
        totalDiseasedCrop: "कुल रोगी फसल",
        totalProduction: "कुल उत्पाद",
        productionDetails: "उत्पाद विवरण",
        jan: "जनवरी",
        feb: "फरवरी",
        mar: "मार्च",
        apr: "अप्रैल",
        may: "मई",
        jun: "जून",
        recentPrecautions: "हाल की बचाव",
        addImage: "छवि जोड़ें",
        recomSize: "अनुशंसित आकार: 165px * 65px",
        checkForDisease: "रोग की जाँच करें",
        expertAdvice: "विशेषज्ञ सलाह",
        disease: "बीमारी",
        crop: "फसल",
        causes: "कारण",
        treatment: "इलाज",
        tutorial: "ट्यूटोरियल",
    },
});

export default setOfStrings;
